### ISSUE TITLE
P71示例结果slice2不对。

### ISSUE THREAD

**Issue by style7en** [F001/rust_book_feedback#32]
slice2的结果应该是
Length: 2
1    2

不是
Length: 2
3    4

**Comment by F001** [comment]
我又试验了一下，应该没错，确实是 [3, 4]。
请注意，`slice2` 是从 `slice` 截取的，而不是从 `arr` 截取的。如果 `slice` 是 [3, 4, 5]，那么它的前两个显然应该是 [3, 4]。

@style7en 如果我的解释有问题，请回复。

**Comment by style7en** [comment]
没问题，是我看岔了，多谢解答。
