### ISSUE TITLE
P31页tiger没有初始值 程序错误 无法绑定和打印

### ISSUE THREAD

**Issue by ParadoxZW** [F001/rust_book_feedback#38]
如题

**Comment by F001** [comment]
@ParadoxZW  我试了一遍，可以编译，可以执行，结果为201，符合预期。
```
rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)
```
请问你用的哪个版本的编译器，源代码以及编译命令？我需要重现方法。

**Comment by ParadoxZW** [comment]
哦 不好意思 我重新看了一下我的代码 有个变量打错了
不过这是为什么啊 tiger明明没有被赋值 为什么转成isize就变成了前面两个的和？

**Comment by F001** [comment]
你理解错了。tiger 不是 dog 和 cat 的和，它只是在 cat 的后面，因此值为 cat + 1。 dog 的值对它没影响。这个规定跟 C/C++/C# 是一致的。如果你有这些语言基础，应该不会感到吃惊。参考 https://en.cppreference.com/w/c/language/enum 。
> If enumerator is followed by = constant-expression, its value is the value of that constant expression. If enumerator is not followed by = constant-expression, its value is the value one greater than the value of the previous enumerator in the same enumeration. The value of the first enumerator (if it does not use = constant-expression) is zero.
