### ISSUE TITLE
几个很小的问题和建议

### ISSUE THREAD

**Issue by KaneGreen** [F001/rust_book_feedback#5]
首先感谢作者的辛勤付出。

我这里提几个很小的问题和建议，可能有些吹毛求疵，也是希望本书变更好更完美。

版本|版次
---|---
纸质版|2018年8月第1版第1次印刷
  
----
### P106
使用`cargo`创建项目时，`1.25.0-stable`以来已经改为默认创建二进制，除非使用`--lib`来创建库。
这里把这个提出来更多的是想告诉新人这里已经发生了一些微小的改变。

----
### P159
建议：本页上部分代码块，`let r2 = r1.clone()`若采用`let r2 = Rc::clone(&r1)`写法，代码可读性更佳，强调了是对Rc指针的clone。TRPL上也采用的是这种写法。
  
一个小失误：本页中间的代码块，`vdata.set(10);`多了个`v`，不过相信大家都应该能看出来。
  
----
### P184
疑问：英文"Easy to Abuse."是否和“不鼓励使用的功能，应该设计得越难用越好。”矛盾？
  
----
### P187
本页正文最后一句话，对代码质量标准的描述中，应为：“不使用unsafe构造出内存不安全”。
  
----
### P205
图19-1，本页图的第一行到第二行，y区域(第一行中的中间和第二行中的右侧)和未初始化的区域(第一行中的右侧和第二行中的中间)交换了位置。给人感觉是这一步还有内存区域的变化，与代码逻辑有出入。
在作本图时，始终保持x区域在左，y区域在中间，未初始化的区域在右，能更容易对照前一页的代码来理解。

**Comment by F001** [comment]
谢谢反馈！
